<?php

namespace App\Controller\Admin\Tool;

use App\Controller\Admin\DashboardController;
use App\Entity\Box;
use App\Enums\UpdateType;
use App\Kernel;
use App\Utils\Coll;
use App\Utils\PDF;
use EasyCorp\Bundle\EasyAdminBundle\Attribute\AdminRoute;
use setasign\Fpdi\Fpdi;
use setasign\Fpdi\PdfReader\PageBoundaries;
use Symfony\Bridge\Twig\Attribute\Template;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class ToolController extends DashboardController
{

    #[Route('/tools')]
    public function index(): Response
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }

    #[AdminRoute('/box-status', name: 'show_box_status')]
    #[Template('admin/tools/box_status.html.twig')]
    public function showBoxStatus(): array
    {
        $boxes = Coll::create($this->rc->getBoxRepo()->findAll());

        return [
            'boxes' => $boxes->map(fn(Box $b) => [
                'id' => $b->getFormattedId(),
                'status' => $b->getLatestStatusUpdate()->Type->value
            ])];
    }

    #[AdminRoute('/update-box-status', name: 'update_box_status')]
    #[Template('admin/tools/update_box_status.html.twig')]
    public function batchUpdateBoxStatus(): array
    {
        return ['update_types' => UpdateType::cases()];
    }

    #[AdminRoute('/create-box-inventory', name: 'create_box_inventory')]
    #[Template('admin/tools/create_box_inventory.html.twig')]
    public function createBoxInventory(): array
    {
        $rows = [[
            'desc' => 'Gem, metall',
            'amount' => 200,
            'comment' => 'Återlämnas',
            'counted' => false
        ]];

        return [
            'topics' => $this->rc->getTopicRepo()->findAll(),
            'rows' => $rows,
        ];
    }

    #[Route('/admin/create-invoice')]
    public function createInvoices(): Response
    {
        $dir = $this->getParameter('kernel.project_dir');

        $pdf = new PDF(new Fpdi(), $dir);

        return new Response($pdf->createInvoices(), 200, [
            'Content-Type' => 'application/pdf'
        ]);
    }

    #[Route('/admin/create-address-labels')]
    public function createAddressLabels(): Response
    {
        $dir = $this->getParameter('kernel.project_dir');

        $pdf = new PDF(new Fpdi(), $dir);

        return new Response($pdf->createAddressLabels(), 200, [
            'Content-Type' => 'application/pdf'
        ]);
    }


}